import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const messages = [
  // Original batch
  "Schlepping...",
  "Combobulating...",
  "Doing...",
  "Channelling...",
  "Vibing...",
  "Concocting...",
  "Spelunking...",
  "Transmuting...",
  "Imagining...",
  "Pontificating...",
  "Whirring...",
  "Cogitating...",
  "Honking...",
  "Flibbertigibbeting...",
  "Noodling...",
  "Percolating...",
  "Ruminating...",
  "Simmering...",
  "Marinating...",
  "Fermenting...",
  "Gestating...",
  "Hatching...",
  "Brewing...",
  "Steeping...",
  "Contemplating...",
  "Musing...",
  "Pondering...",
  "Mulling...",
  "Daydreaming...",
  "Woolgathering...",
  "Dithering...",
  "Faffing...",
  "Puttering...",
  "Tinkering...",
  "Fiddling...",
  "Noodging...",
  "Finagling...",
  "Wrangling...",
  "Jiggling...",
  "Wiggling...",
  "Shimmying...",
  "Galumphing...",
  "Perambulating...",
  "Meandering...",
  "Traipsing...",
  "Moseying...",
  "Sauntering...",
  "Ambling...",
  "Pottering...",
  "Bumbling...",
  "Futzing...",
  "Schmalzing...",
  "Kerfuffling...",
  "Bamboozling...",
  "Discombobulating...",
  "Recombobulating...",
  "Unbefuddling...",
  "Defenestrating...",
  "Confabulating...",
  "Persnicketing...",

  // Creative additions
  "Consulting the void...",
  "Asking the electrons...",
  "Bribing the compiler...",
  "Negotiating with entropy...",
  "Whispering to the bits...",
  "Tickling the stack...",
  "Massaging the heap...",
  "Appeasing the garbage collector...",
  "Summoning semicolons...",
  "Herding pointers...",
  "Untangling spaghetti...",
  "Polishing the algorithms...",
  "Waxing philosophical...",
  "Consulting ancient scrolls...",
  "Reading tea leaves...",
  "Shaking the magic 8-ball...",
  "Sacrificing to the demo gods...",
  "Warming up the hamsters...",
  "Spinning up the squirrels...",
  "Caffeinating...",
  "Existentially questioning...",
  "Having a little think...",
  "Stroking chin thoughtfully...",
  "Squinting at the problem...",
  "Staring into the abyss...",
  "Abyss staring back...",
  "Achieving enlightenment...",
  "Transcending mere computation...",
  "Ascending to a higher plane...",
  "Communing with the machine spirit...",
  "Performing arcane rituals...",
  "Invoking elder functions...",
  "Consulting the oracle...",
  "Divining the answer...",
  "Scrying the codebase...",
  "Dowsing for bugs...",
  "Rearranging deck chairs...",
  "Shuffling bits around...",
  "Aligning the chakras...",
  "Reticulating splines...",
  "Reversing the polarity...",
  "Calibrating the flux capacitor...",
  "Charging the crystals...",
  "Tuning the vibrations...",
  "Adjusting the cosmic frequency...",
  "Waiting for a sign...",
  "Hoping for the best...",
  "Manifesting solutions...",
  "Willing it into existence...",
  "Believing really hard...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
